name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to Datalake
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1

    - name: "Configure AWS Credentials" Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: IaC Apply
      env:
        COMMAND_IAC: terraform
      run: |
        cd terraform-codes
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC apply -auto-approve